In [4]:
import pandas as pd

In [6]:
df = pd.read_csv('terrorism.csv' , encoding = 'latin1')
df.head(5)

C:\Users\colle\AppData\Local\Temp\ipykernel_14472\4294150251.py:1: DtypeWarning: Columns (4,6,31,33,61,62,63,76,79,90,92,94,96,114,115,121) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('terrorism.csv' , encoding = 'latin1')

,eventid,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,region,...,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
0,1.970000e+11,1970,7,2,NaN,0,NaN,58,Dominican Republic,2,...,NaN,NaN,NaN,NaN,PGIS,0,0,0,0,NaN
1,1.970000e+11,1970,0,0,NaN,0,NaN,130,Mexico,1,...,NaN,NaN,NaN,NaN,PGIS,0,1,1,1,NaN
2,1.970010e+11,1970,1,0,NaN,0,NaN,160,Philippines,5,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
3,1.970010e+11,1970,1,0,NaN,0,NaN,78,Greece,8,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
4,1.970010e+11,1970,1,0,NaN,0,NaN,101,Japan,4,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN

In [5]:
df.columns.tolist()

NameError: name 'df' is not defined

In [8]:
newdf = df[[ 
 'iyear',
 'imonth',
 'iday',
 'country_txt',
'region_txt',
 'provstate',
  'city',
 'latitude',
 'longitude',
  'summary',
'attacktype1_txt', 
'weapsubtype1_txt',
'scite1',
 'scite2',
 'scite3',
 
  ]]

newdf

,iyear,imonth,iday,country_txt,region_txt,provstate,city,latitude,longitude,summary,attacktype1_txt,weapsubtype1_txt,scite1,scite2,scite3
0,1970,7,2,Dominican Republic,Central America & Caribbean,NaN,Santo Domingo,18.456792,-69.951164,NaN,Assassination,NaN,NaN,NaN,NaN
1,1970,0,0,Mexico,North America,Federal,Mexico city,19.371887,-99.086624,NaN,Hostage Taking (Kidnapping),NaN,NaN,NaN,NaN
2,1970,1,0,Philippines,Southeast Asia,Tarlac,Unknown,15.478598,120.599741,NaN,Assassination,NaN,NaN,NaN,NaN
3,1970,1,0,Greece,Western Europe,Attica,Athens,37.997490,23.762728,NaN,Bombing/Explosion,Unknown Explosive Type,NaN,NaN,NaN
4,1970,1,0,Japan,East Asia,Fukouka,Fukouka,33.580412,130.396361,NaN,Facility/Infrastructure Attack,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181686,2017,12,31,Somalia,Sub-Saharan Africa,Middle Shebelle,Ceelka Geelow,2.359673,45.385034,12/31/2017: Assailants opened fire on a Somali...,Armed Assault,Unknown Gun Type,"""Somalia: Al-Shabaab Militants Attack Army Che...","""Highlights: Somalia Daily Media Highlights 2 ...","""Highlights: Somalia Daily Media Highlights 1 ..."
181687,2017,12,31,Syria,Middle East & North Africa,Lattakia,Jableh,35.407278,35.942679,12/31/2017: Assailants launched mortars at the...,Bombing/Explosion,"Projectile (rockets, mortars, RPGs, etc.)","""Putin's 'victory' in Syria has turned into a ...","""Two Russian soldiers killed at Hmeymim base i...","""Two Russian servicemen killed in Syria mortar..."
181688,2017,12,31,Philippines,Southeast Asia,Maguindanao,Kubentog,6.900742,124.437908,12/31/2017: Assailants set fire to houses in K...,Facility/Infrastructure Attack,Arson/Fire,"""Maguindanao clashes trap tribe members,"" Phil...",NaN,NaN
181689,2017,12,31,India,South Asia,Manipur,Imphal,24.798346,93.940430,12/31/2017: Assailants threw a grenade at a Fo...,Bombing/Explosion,Grenade,"""Trader escapes grenade attack in Imphal,"" Bus...",NaN,NaN
181690,2017,12,31,Philippines,Southeast Asia,Maguindanao,Cotabato City,7.209594,124.241966,12/31/2017: An explosive device was discovered...,Bombing/Explosion,Unknown Explosive Type,"""Security tightened in Cotabato following IED ...","""Security tightened in Cotabato City,"" Manila ...",NaN

In [23]:
cleandf = newdf.dropna()
cleandf.head(2)
## make a separate dataset

,iyear,imonth,iday,country_txt,region_txt,provstate,city,latitude,longitude,summary,attacktype1_txt,weapsubtype1_txt,scite1,scite2,scite3
5,1970,1,1,United States,North America,Illinois,Cairo,37.005105,-89.176269,1/1/1970: Unknown African American assailants ...,Armed Assault,Unknown Gun Type,"""Police Chief Quits,"" Washington Post, January...","""Cairo Police Chief Quits; Decries Local 'Mili...","Christopher Hewitt, ""Political Violence and Te..."
8,1970,1,2,United States,North America,Wisconsin,Madison,43.076592,-89.412488,"1/2/1970: Karl Armstrong, a member of the New ...",Facility/Infrastructure Attack,Molotov Cocktail/Petrol Bomb,"Tom Bates, ""Rads: The 1970 Bombing of the Army...","David Newman, Sandra Sutherland, and Jon Stewa...","The Wisconsin Cartographers' Guild, ""Wisconsin..."

In [24]:
 cleandf['imonth'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int64)

In [29]:
pd.options.mode.copy_on_write = True
cleandf['month_name'] = pd.to_datetime(cleandf['imonth'], format='%m').dt.month_name()
cleandf

,iyear,imonth,iday,country_txt,region_txt,provstate,city,latitude,longitude,summary,attacktype1_txt,weapsubtype1_txt,scite1,scite2,scite3,month_name
5,1970,1,1,United States,North America,Illinois,Cairo,37.005105,-89.176269,1/1/1970: Unknown African American assailants ...,Armed Assault,Unknown Gun Type,"""Police Chief Quits,"" Washington Post, January...","""Cairo Police Chief Quits; Decries Local 'Mili...","Christopher Hewitt, ""Political Violence and Te...",January
8,1970,1,2,United States,North America,Wisconsin,Madison,43.076592,-89.412488,"1/2/1970: Karl Armstrong, a member of the New ...",Facility/Infrastructure Attack,Molotov Cocktail/Petrol Bomb,"Tom Bates, ""Rads: The 1970 Bombing of the Army...","David Newman, Sandra Sutherland, and Jon Stewa...","The Wisconsin Cartographers' Guild, ""Wisconsin...",January
9,1970,1,3,United States,North America,Wisconsin,Madison,43.072950,-89.386694,"1/3/1970: Karl Armstrong, a member of the New ...",Facility/Infrastructure Attack,Gasoline or Alcohol,Committee on Government Operations United Stat...,"Tom Bates, ""Rads: The 1970 Bombing of the Army...","David Newman, Sandra Sutherland, and Jon Stewa...",January
14,1970,1,9,United States,North America,Puerto Rico,Rio Piedras,18.386932,-66.061127,1/9/1970: The Armed Commandos of Liberation c...,Facility/Infrastructure Attack,Arson/Fire,Committee on the Judiciary United States Sena...,"""No Evidence Of Arson Found In Barkers Fire,"" ...","""Toward People's War for Independence and Soci...",January
17,1970,1,12,United States,North America,New York,New York City,40.697132,-73.931351,1/12/1970: Unknown perpetrators threw a pipe b...,Bombing/Explosion,Pipe Bomb,"""Blast Damages Flatbush School,"" New York Time...","Linda Greenhouse, ""Madison School Puzzled By B...",Committee on Government Operations United Stat...,January
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181675,2017,12,31,Somalia,Sub-Saharan Africa,Banaadir,Mogadishu,2.059819,45.326115,12/31/2017: An explosive device detonated targ...,Bombing/Explosion,Landmine,"""Somalia: Al-Shabab says 5 AU soldiers dead in...","""Somalia: Fifteen Police Officers Complete Tra...","""Two die in Mogadishu bomb attack,"" Xinhua Gen...",December
181677,2017,12,31,Philippines,Southeast Asia,Maguindanao,Limpogo,6.983953,124.420664,12/31/2017: Assailants set fire to at least 12...,Facility/Infrastructure Attack,Unknown Gun Type,"""3 slain in Maguindanao roadside bombings,"" Ph...","""BIFF gunmen torch abandoned houses in Maguind...","""Philippines: Highlights of Terrorist, Counter...",December
181681,2017,12,31,Philippines,Southeast Asia,Maguindanao,Shariff Aguak,6.862806,124.443649,12/31/2017: A roadside bomb detonated targetin...,Bombing/Explosion,Unknown Explosive Type,"""3 dead, scores injured in Mindanao blasts,"" M...","""Cop, 2 others killed in bomb blasts in Mindan...","""Cop killed, 7 injured in Maguindanao IED blas...",December
181686,2017,12,31,Somalia,Sub-Saharan Africa,Middle Shebelle,Ceelka Geelow,2.359673,45.385034,12/31/2017: Assailants opened fire on a Somali...,Armed Assault,Unknown Gun Type,"""Somalia: Al-Shabaab Militants Attack Army Che...","""Highlights: Somalia Daily Media Highlights 2 ...","""Highlights: Somalia Daily Media Highlights 1 ...",December
181687,2017,12,31,Syria,Middle East & North Africa,Lattakia,Jableh,35.407278,35.942679,12/31/2017: Assailants launched mortars at the...,Bombing/Explosion,"Projectile (rockets, mortars, RPGs, etc.)","""Putin's 'victory' in Syria has turned into a ...","""Two Russian soldiers killed at Hmeymim base i...","""Two Russian servicemen killed in Syria mortar...",December

In [44]:
sorted_days = cleandf['iday'].sort_values()
sorted_days.unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31],
      dtype=int64)

In [50]:
#clean summary column to macth the columns that have vulues and the one that has values

cleandf[cleandf['iday'] == 0]

,iyear,imonth,iday,country_txt,region_txt,provstate,city,latitude,longitude,summary,attacktype1_txt,weapsubtype1_txt,scite1,scite2,scite3,month_name
2252,1974,3,0,United States,North America,Colorado,Boulder,40.014986,105.270546,"03/00/1974: In the United States, the Boulder ...",Bombing/Explosion,Unknown Explosive Type,"Marcia McKnight Trick, ""Chronology of Incident...","""Chicano Activists? Bombs Rock Denver,"" The Pr...","Christopher Hewitt, ""Political Violence and Te...",March
5501,1977,11,0,United States,North America,Ohio,Cincinnati,39.103175,-84.511981,11/0/1977: Unknown perpetrators set fire to th...,Facility/Infrastructure Attack,Arson/Fire,"""Ring Around the Rosary,"" Cincinnati Magazine,...","Herman Herst Jr., ""Violence Enters Debate Over...","""Chronological History of Arsons and Bombings ...",November
5891,1978,2,0,United States,North America,Ohio,Cincinnati,39.103175,-84.511981,2/0/1978: Unknown perpetrators threw a chemica...,Bombing/Explosion,Explosive,"Herman Herst Jr., ""Violence Enters Debate Over...","Christopher Hewitt, ""Political Violence and Te...","""Chronological History of Arsons and Bombings ...",February
10870,1980,5,0,United States,North America,Wisconsin,Tomah,43.972570,-90.504769,5/00/1980: Rebecca Bergstrom was picked up by ...,Armed Assault,Handgun,"William G. Blair, ""Slayer A Suspect in 13 More...","""Racist Charged In Slayings,"" The Dispatch, Ma...","Christopher Hewitt, ""Political Violence and Te...",May
31725,1987,8,0,United States,North America,North Dakota,Fargo,46.877257,-96.790247,8/0/1987: Scott P. Garman and an unnamed juven...,Facility/Infrastructure Attack,Molotov Cocktail/Petrol Bomb,"""Latest Arrests Bring Alcohol, Tobacco and Fir...","""Arrest Anti-Abortion Activist,"" The Bryan Tim...","""Chronological History of Arsons and Bombings ...",August
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102844,2011,8,0,Afghanistan,South Asia,Ghazni,Qarabagh,33.193142,68.101852,08/23/2011 (Default date): Between Tuesday and...,Bombing/Explosion,Unknown Explosive Type,"Afghan Islamic Press, ""Eight Mobile Towers Des...","Pajhwok Afghan News, ""Mobile Phone Tower Blown...","BBC Monitoring South Asia, ""Insurgents Destroy...",August
102946,2011,9,0,India,South Asia,Chhattisgarh,Raipur,21.251384,81.629641,"09/01/2011 (Default date): On Thursday, in Rai...",Bombing/Explosion,Other Explosive Type,"South Asia Terrorism Portal, ""Police Recover 2...","Indo-Asian News Service, ""Police Find 25 Kg Bo...","My News, ""Police Find 25 Kg Bomb in Chhattisga...",September
104348,2011,12,0,Thailand,Southeast Asia,Bangkok Province,Bangkok,13.785793,100.560852,12/7/2011: An improvised explosive device (IED...,Bombing/Explosion,Time Fuse,"""Police defuse home-made time bomb planted in ...","""Thailand: Explosive device found on Ratchadam...","""Police defuse six bombs in Bangkok"" Today (Si...",December
104612,2011,12,0,Pakistan,South Asia,Khyber Pakhtunkhwa,Mandeo,32.921246,70.558174,12/0/2011: Sometime during the night between D...,Bombing/Explosion,Other Explosive Type,"""Militants blow up school, house in Bannu,"" Da...","""Blast damages school in Bannu,"" Daily The Pos...","""Pakistan: Militants blow up school, house in ...",December
104613,2011,12,0,Pakistan,South Asia,Khyber Pakhtunkhwa,Mandeo,32.921246,70.558174,12/0/2011: Sometime during the night between ...,Bombing/Explosion,Other Explosive Type,"""Militants blow up school, house in Bannu,"" Da...","""Blast damages school in Bannu,"" Daily The Pos...","""Pakistan: Militants blow up school, house in ...",December